name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install root dev tools
        run: npm ci

      - name: Install client dependencies
        run: npm ci
        working-directory: client

      - name: Install server dependencies
        run: npm ci
        working-directory: server

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier check
        run: npm run format

      - name: Type check client
        run: npm run type-check
        working-directory: client

      - name: Audit dependencies (non-blocking)
        run: npm audit --audit-level=moderate || true

      - name: Build client
        run: npm run build
        working-directory: client

      - name: Deploy to Production Server
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/your-app
            git pull origin main
            npm install
            npm install --prefix server
            npm install --prefix client
            npm run build --prefix client
            pm2 restart all
